# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install easyocr

# ///////////////////////////////////////////////////////////////////////////////////////////////////////////////we need pillow version of 5.3.0
# we will uninstall the older version first
!pip uninstall -y Pillow
# install the new one
!pip install Pillow==5.3.0
# import the new one
import PIL
print(PIL.PILLOW_VERSION)
# this should print 5.3.0. If it doesn't, then restart your runtime:
# Menu > Runtime > Restart Runtime

import matplotlib.pyplot as plt
import cv2
import easyocr
from pylab import rcParams
from IPython.display import Image
import PIL
from PIL import ImageDraw

reader = easyocr.Reader(['en','hi'])

ime = PIL.Image.open("eimage.jpg")
ime

imh = PIL.Image.open("himage.jpg")
imh

ren = reader.readtext("eimage.jpg")
ren

rhi = reader.readtext("himage.jpg")
rhi

def draw_boxes(image,r,color='red',width=0):
    draw = ImageDraw.Draw(image)
    for re in r:
        p0,p1,p2,p3 = re[0]
        draw.line([*p0,*p1,*p2,*p3],fill=color,width=width)
    return image
draw_boxes(ime,r)

draw_boxes(imh,rhi)

for i in r:
    print(i[1])

for x in rhi:
    print(x[1])